// ILE COBOL skeleton generator.  Same protected-region convention as the
// RPGLE one: code inside `[DSPF-RAD-REGION begin=... end=...]` is meant
// to survive regeneration when `previousSource` is supplied.

import {
    collectAids, collectMenuArms, collectPushbtnArms, collectChoiceArms,
    indicatorConditionsOf, usesIndara,
    uniqueRegionKeyGroups, pickMainRecord, pickSubfilePairs,
    pickPulldownRecords, pad2,
} from './analysis.js';
import { ibmiName } from '../model/factories.js';
import { mergeProtectedRegions } from './protectedRegions.js';

export function generateCobol (doc, {
    programName = 'PROGRAM',
    dspfName    = 'DSPF',
    previousSource = null,
} = {}) {
    programName = ibmiName(programName, 'PROGRAM');
    dspfName = ibmiName(dspfName, 'DSPFILE');
    if (!usesIndara(doc)) {
        throw new Error(
            'COBOL generation requires the DSPF INDARA keyword so option ' +
            'and response indicators use a stable 99-position separate area.');
    }
    const aids       = collectAids(doc);
    const sflPairs   = prepareSubfilePairs(pickSubfilePairs(doc));
    const pulldowns  = pickPulldownRecords(doc);
    const mainRecord = pickMainRecord(doc) ?? sflPairs[0]?.sflctl;
    const [menuArms, btnArms, chcArms] = uniqueRegionKeyGroups([
        collectMenuArms(doc), collectPushbtnArms(doc), collectChoiceArms(doc),
    ]);

    const aidEvals   = renderAidEvals(aids);
    const menuBlk    = renderArmsBlock('Menu bar actions', menuArms);
    const btnBlk     = renderArmsBlock('Push buttons',     btnArms);
    const chcBlk     = renderArmsBlock('Choice fields',    chcArms);

    const out = [];
    out.push(...identificationDiv(programName, dspfName, doc));
    out.push(...environmentDiv(dspfName, sflPairs.length > 0));
    out.push(...dataDiv(doc, dspfName, sflPairs));
    out.push(...procedureDiv(
        dspfName, mainRecord, sflPairs, pulldowns,
        aidEvals, menuBlk, btnBlk, chcBlk));
    const generated = out.join('\n') + '\n';
    return mergeProtectedRegions(previousSource, generated);
}

function prepareSubfilePairs (pairs) {
    const seen = new Map();
    return pairs.map((pair, index) => {
        const base = regionPart(pair.sfl.name);
        const count = (seen.get(base) ?? 0) + 1;
        seen.set(base, count);
        return {
            ...pair,
            // Preserve the old first-pair paragraph and region identifiers.
            paragraph: index === 0 ? 'SUBFILE' : `SUBFILE-${pad2(index + 1)}`,
            regionKey: count === 1 ? base : `${base}-${count}`,
        };
    });
}

function regionPart (name) {
    return String(name).toLowerCase().replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '') || 'subfile';
}

// ---- DIVISION builders --------------------------------------------------

function identificationDiv (programName, dspfName, doc) {
    return [
        `       IDENTIFICATION DIVISION.`,
        `       PROGRAM-ID. ${programName}.`,
        `      *>====================================================================`,
        `      *> Program ${programName}`,
        `      *> Generated by DSPF-RAD from ${dspfName}`,
        ...wrapRecordNames('      *> Records: ', doc.records),
        `      *> Edit hint: code inside DSPF-RAD protected-region blocks`,
        `      *>            is preserved across regenerations; everything else is`,
        `      *>            rewritten when you regenerate from the RAD.`,
        `      *>====================================================================`,
    ];
}

function wrapRecordNames (prefix, records, width = 80) {
    const tokens = records.map((record, index) =>
        record.name + (index < records.length - 1 ? ',' : ''));
    const continuation = '      *>          ';
    const lines = [];
    let line = prefix;
    for (const token of tokens) {
        const separator = line === prefix || line === continuation ? '' : ' ';
        if (line.length + separator.length + token.length > width &&
            line !== prefix && line !== continuation) {
            lines.push(line);
            line = continuation + token;
        } else {
            line += separator + token;
        }
    }
    lines.push(line);
    return lines;
}

function environmentDiv (dspfName, hasSubfiles) {
    const lines = [
        `       ENVIRONMENT DIVISION.`,
        `       INPUT-OUTPUT SECTION.`,
        `       FILE-CONTROL.`,
        `           SELECT ${dspfName} ASSIGN TO WORKSTATION-${dspfName}-SI`,
        `                          ORGANIZATION IS TRANSACTION`,
        `                          ACCESS MODE IS ${hasSubfiles ? 'DYNAMIC' : 'SEQUENTIAL'}`,
    ];
    if (hasSubfiles) lines.push(`                          RELATIVE KEY IS WS-SFL-RRN`);
    lines.push(`                          FILE STATUS IS WS-FILE-STATUS.`);
    return lines;
}

function dataDiv (doc, dspfName, sflPairs) {
    const lines = [];
    lines.push(`       DATA DIVISION.`);
    lines.push(`       FILE SECTION.`);
    lines.push(`       FD  ${dspfName}.`);
    lines.push(`       01  ${dspfName}-REC.`);
    lines.push(`           COPY DDS-ALL-FORMATS OF ${dspfName}.`);
    lines.push(`       WORKING-STORAGE SECTION.`);
    lines.push(`       01  WS-FLAGS.`);
    lines.push(`           05  DONE-FLG          PIC X       VALUE "N".`);
    lines.push(`           05  WS-FILE-STATUS    PIC X(2)    VALUE "00".`);
    if (sflPairs.length) {
        lines.push(`           05  WS-SFL-RRN        PIC 9(5)    COMP-4 VALUE 0.`);
    }
    if (sflPairs.length > 1) {
        lines.push(
            `           05  WS-SCREEN         PIC X(10)   VALUE "${sflPairs[0].sflctl.name}".`);
    }
    lines.push(`       01  INDICATORS.`);
    lines.push(`           05  INDIC-TABLE OCCURS 99 PIC 1 INDICATOR 1.`);
    lines.push(`               88  IND-OFF VALUE B"0".`);
    lines.push(`               88  IND-ON  VALUE B"1".`);
    lines.push(``);
    return lines;
}

function procedureDiv (
    dspfName, mainRecord, sflPairs, pulldowns,
    aidEvals, menuBlk, btnBlk, chcBlk,
) {
    const lines = [];
    // Modular paragraphs (ILE COBOL best practice): MAIN-LOGIC just
    // orchestrates init / process / terminate, each phase isolated.
    lines.push(`       PROCEDURE DIVISION.`);
    lines.push(``);
    lines.push(`       MAIN-LOGIC.`);
    lines.push(`           PERFORM INITIALIZE-PROGRAM`);
    lines.push(`           PERFORM PROCESS-SCREEN UNTIL DONE-FLG = "Y"`);
    lines.push(`           PERFORM TERMINATE-PROGRAM`);
    lines.push(`           GOBACK`);
    lines.push(`           .`);
    lines.push(``);
    lines.push(`       INITIALIZE-PROGRAM.`);
    lines.push(`      *> [DSPF-RAD-REGION begin=startup]`);
    lines.push(`      *> Run-once initialisation: open files, fetch parameters, etc.`);
    lines.push(`      *> [DSPF-RAD-REGION end=startup]`);
    lines.push(`           OPEN I-O ${dspfName}`);
    if (pulldowns.length) {
        lines.push(`      *> [DSPF-RAD-REGION begin=prepare-pulldowns]`);
        lines.push(`      *> Populate program-to-system fields used by pulldown choices.`);
        lines.push(`      *> [DSPF-RAD-REGION end=prepare-pulldowns]`);
        for (const record of pulldowns) {
            lines.push(`           WRITE ${dspfName}-REC FORMAT IS "${record.name}"`);
            lines.push(`              INDICATORS ARE INDIC-TABLE`);
            lines.push(`           END-WRITE`);
        }
    }
    lines.push(`           .`);
    lines.push(``);
    lines.push(`       PROCESS-SCREEN.`);
    if (sflPairs.length > 1) {
        lines.push(`      *> [DSPF-RAD-REGION begin=select-subfile-screen]`);
        lines.push(`      *> Set WS-SCREEN to the SFLCTL format that should be interactive.`);
        lines.push(`      *> [DSPF-RAD-REGION end=select-subfile-screen]`);
    }
    lines.push(`      *> [DSPF-RAD-REGION begin=before-display]`);
    lines.push(`      *> Populate fields for the next display operation.`);
    lines.push(`      *> [DSPF-RAD-REGION end=before-display]`);
    if (sflPairs.length === 1) {
        lines.push(`           PERFORM LOAD-${sflPairs[0].paragraph}`);
        lines.push(...renderRecordExchange(dspfName, sflPairs[0].sflctl, '           '));
    } else if (sflPairs.length > 1) {
        lines.push(`           EVALUATE WS-SCREEN`);
        for (const pair of sflPairs) {
            lines.push(`              WHEN "${pair.sflctl.name}"`);
            lines.push(`                 PERFORM LOAD-${pair.paragraph}`);
            lines.push(...renderRecordExchange(dspfName, pair.sflctl, '                 '));
        }
        lines.push(`              WHEN OTHER`);
        lines.push(`                 MOVE "${sflPairs[0].sflctl.name}" TO WS-SCREEN`);
        lines.push(`                 PERFORM LOAD-${sflPairs[0].paragraph}`);
        lines.push(...renderRecordExchange(dspfName, sflPairs[0].sflctl, '                 '));
        lines.push(`           END-EVALUATE`);
    } else if (mainRecord) {
        lines.push(...renderRecordExchange(dspfName, mainRecord, '           '));
    }
    lines.push(`           PERFORM HANDLE-INPUT`);
    lines.push(`           .`);
    lines.push(``);
    lines.push(`       HANDLE-INPUT.`);
    lines.push(`           EVALUATE TRUE`);
    if (aidEvals) lines.push(aidEvals);
    if (menuBlk)  lines.push(menuBlk);
    if (btnBlk)   lines.push(btnBlk);
    if (chcBlk)   lines.push(chcBlk);
    lines.push(`                 WHEN OTHER`);
    lines.push(`      *> [DSPF-RAD-REGION begin=on-enter]`);
    lines.push(`                    CONTINUE`);
    lines.push(`      *> [DSPF-RAD-REGION end=on-enter]`);
    lines.push(...renderChangedSubfileBlocks(sflPairs));
    lines.push(`           END-EVALUATE`);
    lines.push(`           .`);
    lines.push(``);
    for (const pair of sflPairs) lines.push(...loadSubfilePara(pair, dspfName));
    lines.push(`       TERMINATE-PROGRAM.`);
    lines.push(`      *> [DSPF-RAD-REGION begin=shutdown]`);
    lines.push(`      *> Cleanup: close files, log, etc.`);
    lines.push(`      *> [DSPF-RAD-REGION end=shutdown]`);
    lines.push(`           CLOSE ${dspfName}`);
    lines.push(`           .`);
    return lines;
}

function renderRecordExchange (dspfName, record, indent) {
    return [
        `${indent}WRITE ${dspfName}-REC FORMAT IS "${record.name}"`,
        `${indent}   INDICATORS ARE INDIC-TABLE`,
        `${indent}END-WRITE`,
        `${indent}READ ${dspfName} FORMAT IS "${record.name}"`,
        `${indent}   INDICATORS ARE INDIC-TABLE`,
        `${indent}END-READ`,
    ];
}

function renderChangedSubfileBlocks (pairs) {
    const lines = [];
    for (const pair of pairs) {
        lines.push(`      *> Changed rows from ${pair.sfl.name}:`);
        lines.push(`      *> READ SUBFILE NEXT MODIFIED FORMAT IS "${pair.sfl.name}".`);
        lines.push(`      *> [DSPF-RAD-REGION begin=changed-${pair.regionKey}]`);
        lines.push(`                    CONTINUE`);
        lines.push(`      *> [DSPF-RAD-REGION end=changed-${pair.regionKey}]`);
    }
    return lines;
}

function loadSubfilePara (sflPair, dspfName) {
    // SFLCLR / SFLDSP / SFLDSPCTL positions come from indicators on the
    // SFLCTL record.  A missing position just means the user hasn't wired
    // it - we skip its MOVE so the generated code still compiles.
    const clear     = subfileClearOperation(sflPair);
    const sfldsp    = indicatorConditionsOf(sflPair.sflctl, 'SFLDSP');
    const sfldspctl = indicatorConditionsOf(sflPair.sflctl, 'SFLDSPCTL');
    const lkey = sflPair.regionKey;

    const lines = [];
    lines.push(`       LOAD-${sflPair.paragraph}.`);
    lines.push(`      *> [DSPF-RAD-REGION begin=load-${lkey}]`);
    lines.push(`      *> Clear the ${sflPair.sfl.name} subfile, load it record-by-record,`);
    lines.push(`      *> then turn on SFLDSP / SFLDSPCTL so the SFLCTL renders the loaded`);
    lines.push(`      *> subfile on the next WRITE.`);
    lines.push(...renderCobolIndicatorMoves(clear.conditions));
    lines.push(`           WRITE ${dspfName}-REC FORMAT IS "${sflPair.sflctl.name}"`);
    lines.push(`              INDICATORS ARE INDIC-TABLE`);
    lines.push(`           END-WRITE`);
    lines.push(...renderCobolIndicatorMoves(clear.conditions, true));
    lines.push(``);
    lines.push(`           MOVE 0 TO WS-SFL-RRN`);
    lines.push(`      *> Iterate your data source and add records:`);
    lines.push(`      *>   ADD 1 TO WS-SFL-RRN`);
    lines.push(`      *>   ... populate ${sflPair.sfl.name} fields ...`);
    lines.push(`      *>   WRITE SUBFILE ${dspfName}-REC FORMAT IS "${sflPair.sfl.name}"`);
    lines.push(`      *>      INDICATORS ARE INDIC-TABLE`);
    lines.push(`      *>   END-WRITE`);
    lines.push(``);
    lines.push(...renderCobolIndicatorMoves(sfldsp));
    lines.push(...renderCobolIndicatorMoves(sfldspctl));
    lines.push(`      *> [DSPF-RAD-REGION end=load-${lkey}]`);
    lines.push(`           .`);
    lines.push(``);
    return lines;
}

function subfileClearOperation (pair) {
    for (const keyword of ['SFLCLR', 'SFLDLT']) {
        const conditions = indicatorConditionsOf(pair.sflctl, keyword);
        if (conditions.length) return { keyword, conditions };
    }
    return { keyword: 'SFLCLR/SFLDLT', conditions: [] };
}

function renderCobolIndicatorMoves (conditions, invert = false) {
    return conditions.map(condition => {
        const on = invert ? !condition.on : condition.on;
        return `           MOVE B"${on ? '1' : '0'}" TO INDIC-TABLE (${pad2(condition.pos)})`;
    });
}

// ---- evaluate arms -----------------------------------------------------

function renderAidEvals (aids) {
    // Use the positional indicator name (IN03, IN12, …) - friendly names
    // like "Exit" / "Cancel" collide with COBOL reserved words.
    return aids.map(a => {
        const nm = `IN${pad2(a.pos)}`;
        const exitLike = /^C[AF](03|12)$/.test(a.aid);
        return [
            `                 WHEN INDIC-TABLE (${pad2(a.pos)}) = B"1"`,
            `      *> [DSPF-RAD-REGION begin=on-${nm.toLowerCase()}]`,
            `                    ${exitLike ? 'MOVE "Y" TO DONE-FLG' : 'CONTINUE'}`,
            `      *> [DSPF-RAD-REGION end=on-${nm.toLowerCase()}]`,
        ].join('\n');
    }).join('\n');
}

function renderArmsBlock (title, list) {
    if (!list.length) return '';
    const lines = [`      *> ---- ${title} ----`];
    for (const a of list) {
        lines.push(`                 WHEN ${cobolCondition(a.condition)}`);
        lines.push(`      *> ${a.comment}`);
        lines.push(`      *> [DSPF-RAD-REGION begin=${a.regionKey}]`);
        lines.push(`                    CONTINUE`);
        lines.push(`      *> [DSPF-RAD-REGION end=${a.regionKey}]`);
    }
    return lines.join('\n');
}

function cobolCondition (s) {
    return String(s).replace(/\bAnd\b/g, 'AND').replace(/\bOr\b/g, 'OR');
}
