// ILE COBOL skeleton generator.  Same protected-region convention as the
// RPGLE one: code inside `[DSPF-RAD-REGION begin=... end=...]` is meant
// to survive regeneration (caller handles the merge).

import {
    collectAids, collectMenuArms, collectPushbtnArms, collectChoiceArms,
    collectIndicatorPositions, indOfKeyword,
    pickMainRecord, pickSubfilePair, pad2,
} from './analysis.js';

export function generateCobol (doc, {
    programName = 'PROGRAM',
    dspfName    = 'DSPF',
} = {}) {
    const aids       = collectAids(doc);
    const sflPair    = pickSubfilePair(doc);
    const mainRecord = pickMainRecord(doc) ?? sflPair?.sflctl;
    const menuArms   = collectMenuArms(doc);
    const btnArms    = collectPushbtnArms(doc);
    const chcArms    = collectChoiceArms(doc);

    const indicators = emitCobolIndicators(collectIndicatorPositions(doc));
    const aidEvals   = renderAidEvals(aids);
    const menuBlk    = renderArmsBlock('Menu bar actions', menuArms);
    const btnBlk     = renderArmsBlock('Push buttons',     btnArms);
    const chcBlk     = renderArmsBlock('Choice fields',    chcArms);

    const out = [];
    out.push(...identificationDiv(programName, dspfName, doc));
    out.push(...environmentDiv(dspfName));
    out.push(...dataDiv(doc, dspfName, sflPair, indicators));
    out.push(...procedureDiv(
        dspfName, mainRecord, sflPair, aidEvals, menuBlk, btnBlk, chcBlk));
    return out.join('\n') + '\n';
}

// ---- DIVISION builders --------------------------------------------------

function identificationDiv (programName, dspfName, doc) {
    return [
        `       IDENTIFICATION DIVISION.`,
        `       PROGRAM-ID. ${programName}.`,
        `      *>====================================================================`,
        `      *> Program ${programName}`,
        `      *> Generated by DSPF-RAD from ${dspfName}`,
        `      *> Records: ${doc.records.map(r => r.name).join(', ')}`,
        `      *> Edit hint: code inside [DSPF-RAD-REGION begin=... end=...] blocks`,
        `      *>            is preserved across regenerations; everything else is`,
        `      *>            rewritten when you regenerate from the RAD.`,
        `      *>====================================================================`,
    ];
}

function environmentDiv (dspfName) {
    return [
        `       ENVIRONMENT DIVISION.`,
        `       INPUT-OUTPUT SECTION.`,
        `       FILE-CONTROL.`,
        `           SELECT ${dspfName} ASSIGN TO WORKSTATION-${dspfName}`,
        `                          ORGANIZATION IS TRANSACTION`,
        `                          ACCESS MODE IS SEQUENTIAL`,
        `                          FILE STATUS IS WS-FILE-STATUS.`,
    ];
}

function dataDiv (doc, dspfName, sflPair, indicators) {
    const lines = [];
    lines.push(`       DATA DIVISION.`);
    lines.push(`       FILE SECTION.`);
    lines.push(`       FD  ${dspfName}.`);
    // One 01-level buffer per record format under the FD; `COPY DDS-<rec>`
    // is the IBM spelling for pulling DDS field definitions in.
    for (const rec of doc.records) {
        lines.push(`       01  ${rec.name}-REC.`);
        lines.push(`           COPY DDS-${rec.name} OF ${dspfName}.`);
    }
    lines.push(`       WORKING-STORAGE SECTION.`);
    lines.push(`       01  WS-FLAGS.`);
    lines.push(`           05  DONE-FLG          PIC X       VALUE "N".`);
    lines.push(`           05  WS-FILE-STATUS    PIC X(2)    VALUE "00".`);
    if (sflPair) {
        lines.push(`           05  WS-SFL-RRN        PIC S9(4)   COMP-4 VALUE 0.`);
    }
    lines.push(`       01  INDICATORS.`);
    lines.push(indicators);
    lines.push(``);
    return lines;
}

function procedureDiv (
    dspfName, mainRecord, sflPair, aidEvals, menuBlk, btnBlk, chcBlk,
) {
    const lines = [];
    // Modular paragraphs (ILE COBOL best practice): MAIN-LOGIC just
    // orchestrates init / process / terminate, each phase isolated.
    lines.push(`       PROCEDURE DIVISION.`);
    lines.push(``);
    lines.push(`       MAIN-LOGIC.`);
    lines.push(`           PERFORM INITIALIZE-PROGRAM`);
    lines.push(`           PERFORM PROCESS-SCREEN UNTIL DONE-FLG = "Y"`);
    lines.push(`           PERFORM TERMINATE-PROGRAM`);
    lines.push(`           GOBACK`);
    lines.push(`           .`);
    lines.push(``);
    lines.push(`       INITIALIZE-PROGRAM.`);
    lines.push(`      *> [DSPF-RAD-REGION begin=startup]`);
    lines.push(`      *> Run-once initialisation: open files, fetch parameters, etc.`);
    lines.push(`      *> [DSPF-RAD-REGION end=startup]`);
    lines.push(`           OPEN I-O ${dspfName}`);
    lines.push(`           .`);
    lines.push(``);
    lines.push(`       PROCESS-SCREEN.`);
    if (sflPair) lines.push(`           PERFORM LOAD-SUBFILE`);
    if (mainRecord) {
        lines.push(`           WRITE ${mainRecord.name}-REC FORMAT IS "${mainRecord.name}"`);
        lines.push(`              INDICATORS ARE INDICATORS`);
        lines.push(`           END-WRITE`);
        lines.push(`           READ ${dspfName} FORMAT IS "${mainRecord.name}"`);
        lines.push(`              INDICATORS ARE INDICATORS`);
        lines.push(`           END-READ`);
    }
    lines.push(`           PERFORM HANDLE-INPUT`);
    lines.push(`           .`);
    lines.push(``);
    lines.push(`       HANDLE-INPUT.`);
    lines.push(`           EVALUATE TRUE`);
    if (aidEvals) lines.push(aidEvals);
    if (menuBlk)  lines.push(menuBlk);
    if (btnBlk)   lines.push(btnBlk);
    if (chcBlk)   lines.push(chcBlk);
    lines.push(`                 WHEN OTHER`);
    lines.push(`      *> [DSPF-RAD-REGION begin=on-enter]`);
    lines.push(`                    CONTINUE`);
    lines.push(`      *> [DSPF-RAD-REGION end=on-enter]`);
    lines.push(`           END-EVALUATE`);
    lines.push(`           .`);
    lines.push(``);
    if (sflPair) lines.push(...loadSubfilePara(sflPair));
    lines.push(`       TERMINATE-PROGRAM.`);
    lines.push(`      *> [DSPF-RAD-REGION begin=shutdown]`);
    lines.push(`      *> Cleanup: close files, log, etc.`);
    lines.push(`      *> [DSPF-RAD-REGION end=shutdown]`);
    lines.push(`           CLOSE ${dspfName}`);
    lines.push(`           .`);
    return lines;
}

function loadSubfilePara (sflPair) {
    // SFLCLR / SFLDSP / SFLDSPCTL positions come from indicators on the
    // SFLCTL record.  A missing position just means the user hasn't wired
    // it — we skip its MOVE so the generated code still compiles.
    const sflclrPos    = indOfKeyword(sflPair.sflctl, 'SFLCLR');
    const sfldspPos    = indOfKeyword(sflPair.sflctl, 'SFLDSP');
    const sfldspctlPos = indOfKeyword(sflPair.sflctl, 'SFLDSPCTL');
    const lkey = sflPair.sfl.name.toLowerCase();

    const lines = [];
    lines.push(`       LOAD-SUBFILE.`);
    lines.push(`      *> [DSPF-RAD-REGION begin=load-${lkey}]`);
    lines.push(`      *> Clear the ${sflPair.sfl.name} subfile, load it record-by-record,`);
    lines.push(`      *> then turn on SFLDSP / SFLDSPCTL so the SFLCTL renders the loaded`);
    lines.push(`      *> subfile on the next WRITE.`);
    if (sflclrPos != null) {
        lines.push(`           MOVE B"1" TO IN${pad2(sflclrPos)}`);
    }
    lines.push(`           WRITE ${sflPair.sflctl.name}-REC FORMAT IS "${sflPair.sflctl.name}"`);
    lines.push(`              INDICATORS ARE INDICATORS`);
    lines.push(`           END-WRITE`);
    if (sflclrPos != null) {
        lines.push(`           MOVE B"0" TO IN${pad2(sflclrPos)}`);
    }
    lines.push(``);
    lines.push(`           MOVE 0 TO WS-SFL-RRN`);
    lines.push(`      *> Iterate your data source and add records:`);
    lines.push(`      *>   ADD 1 TO WS-SFL-RRN`);
    lines.push(`      *>   ... populate ${sflPair.sfl.name}-REC fields ...`);
    lines.push(`      *>   WRITE ${sflPair.sfl.name}-REC FORMAT IS "${sflPair.sfl.name}"`);
    lines.push(`      *>      INDICATORS ARE INDICATORS`);
    lines.push(`      *>   END-WRITE`);
    lines.push(``);
    if (sfldspPos    != null) lines.push(`           MOVE B"1" TO IN${pad2(sfldspPos)}`);
    if (sfldspctlPos != null) lines.push(`           MOVE B"1" TO IN${pad2(sfldspctlPos)}`);
    lines.push(`      *> [DSPF-RAD-REGION end=load-${lkey}]`);
    lines.push(`           .`);
    lines.push(``);
    return lines;
}

// ---- indicator group ---------------------------------------------------

// Build the inside of `01 INDICATORS.` as a 99-byte positional area.
// Referenced positions get a named IN<nn> slot; gaps become FILLER bytes
// so the structure spans the full 99 positions COBOL maps onto the file.
function emitCobolIndicators (positions) {
    if (!positions.length) {
        return `           05  FILLER      PIC X(99).`;
    }
    const sorted = [...positions].sort((a, b) => a - b);
    const lines  = [];
    let prev = 0;
    for (const pos of sorted) {
        const gap = pos - prev - 1;
        if (gap > 0) lines.push(`           05  FILLER      PIC X(${gap}).`);
        lines.push(`           05  IN${pad2(pos)}        PIC 1.`);
        prev = pos;
    }
    if (prev < 99) lines.push(`           05  FILLER      PIC X(${99 - prev}).`);
    return lines.join('\n');
}

// ---- evaluate arms -----------------------------------------------------

function renderAidEvals (aids) {
    // Use the positional indicator name (IN03, IN12, …) — friendly names
    // like "Exit" / "Cancel" collide with COBOL reserved words.
    return aids.map(a => {
        const nm = `IN${pad2(a.pos)}`;
        const exitLike = a.aid === 'CA03' || a.aid === 'CA12';
        return [
            `                 WHEN ${nm} = B"1"`,
            `      *> [DSPF-RAD-REGION begin=on-${nm.toLowerCase()}]`,
            `                    ${exitLike ? 'MOVE "Y" TO DONE-FLG' : 'CONTINUE'}`,
            `      *> [DSPF-RAD-REGION end=on-${nm.toLowerCase()}]`,
        ].join('\n');
    }).join('\n');
}

function renderArmsBlock (title, list) {
    if (!list.length) return '';
    const lines = [`      *> ---- ${title} ----`];
    for (const a of list) {
        lines.push(`                 WHEN ${cobolCondition(a.condition)}`);
        lines.push(`      *> ${a.comment}`);
        lines.push(`      *> [DSPF-RAD-REGION begin=${a.regionKey}]`);
        lines.push(`                    CONTINUE`);
        lines.push(`      *> [DSPF-RAD-REGION end=${a.regionKey}]`);
    }
    return lines.join('\n');
}

function cobolCondition (s) {
    return String(s).replace(/\bAnd\b/g, 'AND').replace(/\bOr\b/g, 'OR');
}
