// RPGLE skeleton generator.  Emits a `**FREE` program with protected
// regions — code inside `[DSPF-RAD-REGION begin=... end=...]` blocks is
// preserved across regenerations (caller is responsible for the merge).

import {
    collectAids, collectMenuArms, collectPushbtnArms, collectChoiceArms,
    pickMainRecord, pickSubfilePair, pad2,
} from './analysis.js';

export function generateRpgle (doc, {
    programName = 'PROGRAM',
    dspfName    = 'DSPF',
} = {}) {
    const aids       = collectAids(doc);
    const mainRecord = pickMainRecord(doc);
    const sflPair    = pickSubfilePair(doc);
    const menuArms   = collectMenuArms(doc);
    const btnArms    = collectPushbtnArms(doc);
    const chcArms    = collectChoiceArms(doc);

    const indDS    = renderIndDS(aids);
    const aidArms  = renderAidArms(aids);
    const menuBlk  = renderArmsBlock('Menu bar actions', menuArms);
    const btnBlk   = renderArmsBlock('Push buttons',     btnArms);
    const chcBlk   = renderArmsBlock('Choice fields',    chcArms);

    const out = [];
    out.push(`**FREE`);
    out.push(``);
    out.push(...prologue(programName, dspfName, doc));
    out.push(``);
    out.push(`Ctl-Opt Main(${programName}_main) DftActGrp(*No) BndDir('QC2LE');`);
    out.push(``);
    out.push(`Dcl-F ${dspfName} Workstn IndDS(WkInd) UsrOpn;`);
    out.push(``);
    out.push(`Dcl-Ds WkInd Qualified;`);
    out.push(indDS || `  // (no CA/CF keywords found on records)`);
    out.push(`End-Ds;`);
    out.push(``);
    out.push(`Dcl-Proc ${programName}_main;`);
    out.push(`  Dcl-S done Ind Inz(*Off);`);
    out.push(``);
    out.push(`  // [DSPF-RAD-REGION begin=startup]`);
    out.push(`  // Run-once initialisation (open files, fetch parameters, ...).`);
    out.push(`  // [DSPF-RAD-REGION end=startup]`);
    out.push(``);
    out.push(`  Open ${dspfName};`);
    out.push(`  Dou done;`);
    out.push(...renderDisplayLoop(sflPair, mainRecord, dspfName));
    out.push(``);
    out.push(`    Select;`);
    if (aidArms)  out.push(aidArms);
    if (menuBlk)  out.push(menuBlk);
    if (btnBlk)   out.push(btnBlk);
    if (chcBlk)   out.push(chcBlk);
    out.push(...renderOtherArm(sflPair, dspfName));
    out.push(`    EndSl;`);
    out.push(`  EndDo;`);
    out.push(``);
    out.push(`  Close ${dspfName};`);
    out.push(`  // [DSPF-RAD-REGION begin=shutdown]`);
    out.push(`  // Cleanup (close files, log, ...).`);
    out.push(`  // [DSPF-RAD-REGION end=shutdown]`);
    out.push(`  Return;`);
    out.push(`End-Proc;`);

    return out.join('\n') + '\n';
}

function prologue (programName, dspfName, doc) {
    return [
        `// =====================================================================`,
        `// Program ${programName}`,
        `// Generated by DSPF-RAD from ${dspfName}`,
        `// Source records: ${doc.records.map(r => r.name).join(', ')}`,
        `// Edit hint: code inside [DSPF-RAD-REGION begin=... end=...] blocks is`,
        `//            preserved across regenerations.  Everything outside the`,
        `//            regions is rewritten when you regenerate from the RAD.`,
        `// =====================================================================`,
    ];
}

function renderIndDS (aids) {
    return aids.map(aid =>
        `  ${aid.field.padEnd(8)} Ind Pos(${pad2(aid.pos)});`).join('\n');
}

function renderAidArms (aids) {
    return aids.map(aid => {
        const key        = aid.field;
        const isExitLike = aid.aid === 'CA03' || aid.aid === 'CA12';
        const inner      = isExitLike ? `done = *On;` : '';
        return [
            `      When WkInd.${key};`,
            `        // [DSPF-RAD-REGION begin=on-${key.toLowerCase()}]`,
            `        ${inner}`.trimEnd(),
            `        // [DSPF-RAD-REGION end=on-${key.toLowerCase()}]`,
        ].filter(Boolean).join('\n');
    }).join('\n');
}

function renderArmsBlock (title, list) {
    if (!list.length) return '';
    const lines = [`      // ---- ${title} ----`];
    for (const a of list) {
        lines.push(`      When ${a.condition};`);
        lines.push(`        // ${a.comment}`);
        lines.push(`        // [DSPF-RAD-REGION begin=${a.regionKey}]`);
        lines.push(`        // [DSPF-RAD-REGION end=${a.regionKey}]`);
    }
    return lines.join('\n');
}

function renderDisplayLoop (sflPair, mainRecord, dspfName) {
    const out = [];
    if (sflPair) {
        const lkey = sflPair.sfl.name.toLowerCase();
        out.push(`    // [DSPF-RAD-REGION begin=load-${lkey}]`);
        out.push(`    // Fill ${sflPair.sfl.name} subfile records here.  Suggested skeleton:`);
        out.push(`    //   *In30 = *On;  Write ${sflPair.sflctl.name};  *In30 = *Off;  // SFLCLR`);
        out.push(`    //   Dou %Eof(...);`);
        out.push(`    //     Read your data source ...`);
        out.push(`    //     Write ${sflPair.sfl.name};`);
        out.push(`    //   EndDo;`);
        out.push(`    //   *In31 = *On;  // SFLDSP`);
        out.push(`    //   *In32 = *On;  // SFLDSPCTL`);
        out.push(`    // [DSPF-RAD-REGION end=load-${lkey}]`);
        out.push(``);
        out.push(`    Exfmt ${sflPair.sflctl.name};`);
    } else if (mainRecord) {
        out.push(``);
        out.push(`    Exfmt ${mainRecord.name};`);
    } else {
        out.push(`    // No suitable record found - add Exfmt for your main display.`);
    }
    return out;
}

function renderOtherArm (sflPair, dspfName) {
    const out = [];
    out.push(`      Other;`);
    out.push(`        // [DSPF-RAD-REGION begin=on-enter]`);
    out.push(`        // Handle Enter / data-bearing AID keys with no more specific match.`);
    if (sflPair) {
        out.push(`        // Example subfile read loop:`);
        out.push(`        //   ReadC ${sflPair.sfl.name};`);
        out.push(`        //   Dow Not %Eof(${dspfName});`);
        out.push(`        //     // process changed row`);
        out.push(`        //     ReadC ${sflPair.sfl.name};`);
        out.push(`        //   EndDo;`);
    }
    out.push(`        // [DSPF-RAD-REGION end=on-enter]`);
    return out;
}
