// Skeleton generators for RPGLE / COBOL code-behind, scaffolded from a
// DspfDocument.  Output uses "protected region" markers so the user can
// regenerate after DSPF changes without losing hand-written logic
// inside the regions.
//
// Region marker convention:
//   // [DSPF-RAD-REGION begin=<key>]
//   ... user code preserved across regenerations ...
//   // [DSPF-RAD-REGION end=<key>]
//
// The current generators always emit empty regions.  A future "merge"
// pass can be added to splice prior region bodies into a fresh skeleton.

const AID_DESCRIPTIONS = {
    CA01: 'PF1',  CA02: 'PF2',  CA03: 'Exit',   CA04: 'PF4',
    CA05: 'PF5',  CA06: 'PF6',  CA07: 'PF7',    CA08: 'PF8',
    CA09: 'PF9',  CA10: 'PF10', CA11: 'PF11',   CA12: 'Cancel',
    CA13: 'PF13', CA14: 'PF14', CA15: 'PF15',   CA16: 'PF16',
    CA17: 'PF17', CA18: 'PF18', CA19: 'PF19',   CA20: 'PF20',
    CA21: 'PF21', CA22: 'PF22', CA23: 'PF23',   CA24: 'PF24',
    CF01: 'PF1',  CF02: 'PF2',  CF03: 'Exit',   CF04: 'PF4',
    CF05: 'PF5',  CF06: 'PF6',  CF07: 'PF7',    CF08: 'PF8',
    CF09: 'PF9',  CF10: 'PF10', CF11: 'PF11',   CF12: 'Cancel',
    CF13: 'PF13', CF14: 'PF14', CF15: 'PF15',   CF16: 'PF16',
    CF17: 'PF17', CF18: 'PF18', CF19: 'PF19',   CF20: 'PF20',
    CF21: 'PF21', CF22: 'PF22', CF23: 'PF23',   CF24: 'PF24',
    HELP: 'Help', HOME: 'Home', PRINT: 'Print', CLEAR: 'Clear',
    ROLLUP:    'RollUp',     ROLLDOWN:   'RollDown',
    PAGEUP:    'PageUp',     PAGEDOWN:   'PageDown',
    ALTPAGEUP: 'AltPageUp',  ALTPAGEDWN: 'AltPageDn',
    ALTHELP:   'AltHelp',    RETKEY:     'RetKey',
    MNUCNL:    'MenuCancel',
};

// ---------------------------------------------------------------- RPGLE

export function generateRpgle (doc, { programName = 'PROGRAM', dspfName = 'DSPF' } = {}) {
    const aids = collectAids(doc);
    const mainRecord = pickMainRecord(doc);
    const sflPair = pickSubfilePair(doc);
    const menuArms = collectMenuArms(doc);
    const btnArms  = collectPushbtnArms(doc);
    const chcArms  = collectChoiceArms(doc);

    const indDS = aids.map(aid =>
        `  ${aid.field.padEnd(8)} Ind Pos(${pad2(aid.pos)});`).join('\n');

    const aidArms = aids.map(aid => {
        const key = aid.field;
        const isExitLike = aid.aid === 'CA03' || aid.aid === 'CA12';
        const inner = isExitLike ? `done = *On;` : '';
        return [
            `      When WkInd.${key};`,
            `        // [DSPF-RAD-REGION begin=on-${key.toLowerCase()}]`,
            `        ${inner}`.trimEnd(),
            `        // [DSPF-RAD-REGION end=on-${key.toLowerCase()}]`,
        ].filter(Boolean).join('\n');
    }).join('\n');

    const armsBlock = (title, list) => {
        if (!list.length) return '';
        const lines = [`      // ---- ${title} ----`];
        for (const a of list) {
            lines.push(`      When ${a.condition};`);
            lines.push(`        // ${a.comment}`);
            lines.push(`        // [DSPF-RAD-REGION begin=${a.regionKey}]`);
            lines.push(`        // [DSPF-RAD-REGION end=${a.regionKey}]`);
        }
        return lines.join('\n');
    };

    const menuBlock = armsBlock('Menu bar actions', menuArms);
    const btnBlock  = armsBlock('Push buttons',     btnArms);
    const chcBlock  = armsBlock('Choice fields',    chcArms);

    const out = [];
    out.push(`**FREE`);
    out.push(``);
    out.push(`// =====================================================================`);
    out.push(`// Program ${programName}`);
    out.push(`// Generated by DSPF-RAD from ${dspfName}`);
    out.push(`// Source records: ${doc.records.map(r => r.name).join(', ')}`);
    out.push(`// Edit hint: code inside [DSPF-RAD-REGION begin=... end=...] blocks is`);
    out.push(`//            preserved across regenerations.  Everything outside the`);
    out.push(`//            regions is rewritten when you regenerate from the RAD.`);
    out.push(`// =====================================================================`);
    out.push(``);
    out.push(`Ctl-Opt Main(${programName}_main) DftActGrp(*No) BndDir('QC2LE');`);
    out.push(``);
    out.push(`Dcl-F ${dspfName} Workstn IndDS(WkInd) UsrOpn;`);
    out.push(``);
    out.push(`Dcl-Ds WkInd Qualified;`);
    out.push(indDS || `  // (no CA/CF keywords found on records)`);
    out.push(`End-Ds;`);
    out.push(``);
    out.push(`Dcl-Proc ${programName}_main;`);
    out.push(`  Dcl-S done Ind Inz(*Off);`);
    out.push(``);
    out.push(`  // [DSPF-RAD-REGION begin=startup]`);
    out.push(`  // Run-once initialisation (open files, fetch parameters, ...).`);
    out.push(`  // [DSPF-RAD-REGION end=startup]`);
    out.push(``);
    out.push(`  Open ${dspfName};`);
    out.push(`  Dou done;`);
    if (sflPair) {
        out.push(`    // [DSPF-RAD-REGION begin=load-${sflPair.sfl.name.toLowerCase()}]`);
        out.push(`    // Fill ${sflPair.sfl.name} subfile records here.  Suggested skeleton:`);
        out.push(`    //   *In30 = *On;  Write ${sflPair.sflctl.name};  *In30 = *Off;  // SFLCLR`);
        out.push(`    //   Dou %Eof(...);`);
        out.push(`    //     Read your data source ...`);
        out.push(`    //     Write ${sflPair.sfl.name};`);
        out.push(`    //   EndDo;`);
        out.push(`    //   *In31 = *On;  // SFLDSP`);
        out.push(`    //   *In32 = *On;  // SFLDSPCTL`);
        out.push(`    // [DSPF-RAD-REGION end=load-${sflPair.sfl.name.toLowerCase()}]`);
        out.push(``);
        out.push(`    Exfmt ${sflPair.sflctl.name};`);
    } else if (mainRecord) {
        out.push(``);
        out.push(`    Exfmt ${mainRecord.name};`);
    } else {
        out.push(`    // No suitable record found - add Exfmt for your main display.`);
    }
    out.push(``);
    out.push(`    Select;`);
    if (aidArms)   out.push(aidArms);
    if (menuBlock) out.push(menuBlock);
    if (btnBlock)  out.push(btnBlock);
    if (chcBlock)  out.push(chcBlock);
    out.push(`      Other;`);
    out.push(`        // [DSPF-RAD-REGION begin=on-enter]`);
    out.push(`        // Handle Enter / data-bearing AID keys with no more specific match.`);
    if (sflPair) {
        out.push(`        // Example subfile read loop:`);
        out.push(`        //   ReadC ${sflPair.sfl.name};`);
        out.push(`        //   Dow Not %Eof(${dspfName});`);
        out.push(`        //     // process changed row`);
        out.push(`        //     ReadC ${sflPair.sfl.name};`);
        out.push(`        //   EndDo;`);
    }
    out.push(`        // [DSPF-RAD-REGION end=on-enter]`);
    out.push(`    EndSl;`);
    out.push(`  EndDo;`);
    out.push(``);
    out.push(`  Close ${dspfName};`);
    out.push(`  // [DSPF-RAD-REGION begin=shutdown]`);
    out.push(`  // Cleanup (close files, log, ...).`);
    out.push(`  // [DSPF-RAD-REGION end=shutdown]`);
    out.push(`  Return;`);
    out.push(`End-Proc;`);

    return out.join('\n') + '\n';
}

// ---------------------------------------------------------------- COBOL

/** Build the inside of `01 INDICATORS.` as a 99-byte positional area.
 *  Every indicator position the document actually references (AID,
 *  conditioning, SFL control) gets a named IN<nn> slot; the gaps between
 *  them are FILLER bytes so the structure spans the full 99-position
 *  indicator area that IBM ILE COBOL's WRITE/READ "INDICATORS ARE" clause
 *  maps byte-for-byte onto the display file. */
function emitCobolIndicators (positions) {
    if (!positions.length) {
        return `           05  FILLER      PIC X(99).`;
    }
    const sorted = [...positions].sort((a, b) => a - b);
    const lines = [];
    let prev = 0;
    for (const pos of sorted) {
        const gap = pos - prev - 1;
        if (gap > 0) {
            lines.push(`           05  FILLER      PIC X(${gap}).`);
        }
        lines.push(`           05  IN${pad2(pos)}        PIC 1.`);
        prev = pos;
    }
    if (prev < 99) {
        lines.push(`           05  FILLER      PIC X(${99 - prev}).`);
    }
    return lines.join('\n');
}

/** Every indicator position referenced anywhere in the document: AIDs
 *  (CA/CF/HELP/...), record/item conditioning, conditioned keywords like
 *  SFLDSP / SFLCLR.  Each one becomes a named slot in the 99-byte area
 *  so user code can MOVE B"1" TO IN<nn> or compare it in EVALUATE arms. */
function collectIndicatorPositions (doc) {
    const positions = new Set();
    const harvest = (target) => {
        if (!target) return;
        for (const ind of target.indicators ?? []) {
            const m = String(ind).match(/^N?(\d{1,2})$/);
            if (m) positions.add(parseInt(m[1], 10));
        }
        for (const kw of target.keywords ?? []) {
            for (const ind of kw.indicators ?? []) {
                const m = String(ind).match(/^N?(\d{1,2})$/);
                if (m) positions.add(parseInt(m[1], 10));
            }
        }
    };
    for (const rec of doc.records) {
        harvest(rec);
        for (const item of rec.items) harvest(item);
    }
    // AIDs often carry the indicator number as an arg (CA03(03)) rather
    // than via the conditioning slot - mix those in too.
    for (const a of collectAids(doc)) positions.add(a.pos);
    return [...positions].sort((a, b) => a - b);
}

/** Indicator position attached to a keyword's conditioning slot, or null.
 *  Used by the SFL loader to recover the SFLCLR / SFLDSP / SFLDSPCTL
 *  numbers the user wired into the SFLCTL record. */
function indOfKeyword (target, name) {
    const kw = target.keywords?.find(k => k.name === name);
    if (!kw) return null;
    const ind = kw.indicators?.[0];
    if (!ind) return null;
    const m = String(ind).match(/^N?(\d{1,2})$/);
    return m ? parseInt(m[1], 10) : null;
}

export function generateCobol (doc, { programName = 'PROGRAM', dspfName = 'DSPF' } = {}) {
    const aids = collectAids(doc);
    const sflPair = pickSubfilePair(doc);
    const mainRecord = pickMainRecord(doc) ?? sflPair?.sflctl;
    const menuArms = collectMenuArms(doc);
    const btnArms  = collectPushbtnArms(doc);
    const chcArms  = collectChoiceArms(doc);

    const indicators = emitCobolIndicators(collectIndicatorPositions(doc));

    // AID branches use the positional indicator name (IN03, IN12, ...).
    // Friendly names (Exit, Cancel) collide with COBOL reserved words and
    // would be rejected by the compiler.
    const aidEvals = aids.map(a => {
        const nm = `IN${pad2(a.pos)}`;
        const exitLike = a.aid === 'CA03' || a.aid === 'CA12';
        return [
            `                 WHEN ${nm} = B"1"`,
            `      *> [DSPF-RAD-REGION begin=on-${nm.toLowerCase()}]`,
            `                    ${exitLike ? 'MOVE "Y" TO DONE-FLG' : 'CONTINUE'}`,
            `      *> [DSPF-RAD-REGION end=on-${nm.toLowerCase()}]`,
        ].join('\n');
    }).join('\n');

    const cobolArms = (title, list) => {
        if (!list.length) return '';
        const lines = [`      *> ---- ${title} ----`];
        for (const a of list) {
            lines.push(`                 WHEN ${cobolCondition(a.condition)}`);
            lines.push(`      *> ${a.comment}`);
            lines.push(`      *> [DSPF-RAD-REGION begin=${a.regionKey}]`);
            lines.push(`                    CONTINUE`);
            lines.push(`      *> [DSPF-RAD-REGION end=${a.regionKey}]`);
        }
        return lines.join('\n');
    };
    const menuBlock = cobolArms('Menu bar actions', menuArms);
    const btnBlock  = cobolArms('Push buttons',     btnArms);
    const chcBlock  = cobolArms('Choice fields',    chcArms);

    const out = [];

    // ---- IDENTIFICATION / ENVIRONMENT ---------------------------------
    out.push(`       IDENTIFICATION DIVISION.`);
    out.push(`       PROGRAM-ID. ${programName}.`);
    out.push(`      *>====================================================================`);
    out.push(`      *> Program ${programName}`);
    out.push(`      *> Generated by DSPF-RAD from ${dspfName}`);
    out.push(`      *> Records: ${doc.records.map(r => r.name).join(', ')}`);
    out.push(`      *> Edit hint: code inside [DSPF-RAD-REGION begin=... end=...] blocks`);
    out.push(`      *>            is preserved across regenerations; everything else is`);
    out.push(`      *>            rewritten when you regenerate from the RAD.`);
    out.push(`      *>====================================================================`);
    out.push(`       ENVIRONMENT DIVISION.`);
    out.push(`       INPUT-OUTPUT SECTION.`);
    out.push(`       FILE-CONTROL.`);
    out.push(`           SELECT ${dspfName} ASSIGN TO WORKSTATION-${dspfName}`);
    out.push(`                          ORGANIZATION IS TRANSACTION`);
    out.push(`                          ACCESS MODE IS SEQUENTIAL`);
    out.push(`                          FILE STATUS IS WS-FILE-STATUS.`);

    // ---- DATA DIVISION ------------------------------------------------
    out.push(`       DATA DIVISION.`);
    out.push(`       FILE SECTION.`);
    out.push(`       FD  ${dspfName}.`);
    // One 01-level buffer per record format under the FD; COBOL allows
    // multiple record descriptions for a single FD, each an alternate
    // view of the same display-file buffer.  `COPY DDS-<rec> OF <file>`
    // is the IBM-mandated spelling for pulling DDS field definitions in.
    for (const rec of doc.records) {
        out.push(`       01  ${rec.name}-REC.`);
        out.push(`           COPY DDS-${rec.name} OF ${dspfName}.`);
    }
    out.push(`       WORKING-STORAGE SECTION.`);
    out.push(`       01  WS-FLAGS.`);
    out.push(`           05  DONE-FLG          PIC X       VALUE "N".`);
    out.push(`           05  WS-FILE-STATUS    PIC X(2)    VALUE "00".`);
    if (sflPair) {
        out.push(`           05  WS-SFL-RRN        PIC S9(4)   COMP-4 VALUE 0.`);
    }
    out.push(`       01  INDICATORS.`);
    out.push(indicators);
    out.push(``);

    // ---- PROCEDURE DIVISION -------------------------------------------
    // Modular paragraphs (ILE COBOL best practice): the high-level
    // MAIN-LOGIC just orchestrates init / process-loop / terminate, and
    // each phase lives in its own paragraph so PERFORM gives clean
    // single-purpose calls and the regen-protected regions land in
    // predictable places.
    out.push(`       PROCEDURE DIVISION.`);
    out.push(``);
    out.push(`       MAIN-LOGIC.`);
    out.push(`           PERFORM INITIALIZE-PROGRAM`);
    out.push(`           PERFORM PROCESS-SCREEN UNTIL DONE-FLG = "Y"`);
    out.push(`           PERFORM TERMINATE-PROGRAM`);
    out.push(`           GOBACK`);
    out.push(`           .`);
    out.push(``);
    out.push(`       INITIALIZE-PROGRAM.`);
    out.push(`      *> [DSPF-RAD-REGION begin=startup]`);
    out.push(`      *> Run-once initialisation: open files, fetch parameters, etc.`);
    out.push(`      *> [DSPF-RAD-REGION end=startup]`);
    out.push(`           OPEN I-O ${dspfName}`);
    out.push(`           .`);
    out.push(``);
    out.push(`       PROCESS-SCREEN.`);
    if (sflPair) {
        out.push(`           PERFORM LOAD-SUBFILE`);
    }
    if (mainRecord) {
        out.push(`           WRITE ${mainRecord.name}-REC FORMAT IS "${mainRecord.name}"`);
        out.push(`              INDICATORS ARE INDICATORS`);
        out.push(`           END-WRITE`);
        out.push(`           READ ${dspfName} FORMAT IS "${mainRecord.name}"`);
        out.push(`              INDICATORS ARE INDICATORS`);
        out.push(`           END-READ`);
    }
    out.push(`           PERFORM HANDLE-INPUT`);
    out.push(`           .`);
    out.push(``);
    out.push(`       HANDLE-INPUT.`);
    out.push(`           EVALUATE TRUE`);
    if (aidEvals)  out.push(aidEvals);
    if (menuBlock) out.push(menuBlock);
    if (btnBlock)  out.push(btnBlock);
    if (chcBlock)  out.push(chcBlock);
    out.push(`                 WHEN OTHER`);
    out.push(`      *> [DSPF-RAD-REGION begin=on-enter]`);
    out.push(`                    CONTINUE`);
    out.push(`      *> [DSPF-RAD-REGION end=on-enter]`);
    out.push(`           END-EVALUATE`);
    out.push(`           .`);
    out.push(``);
    if (sflPair) {
        // SFLCLR / SFLDSP / SFLDSPCTL positions come from the indicators
        // attached to those conditioned keywords on the SFLCTL record;
        // a missing one just means the user hasn't wired it (the loader
        // skips the corresponding MOVE so the generated code still compiles).
        const sflclrPos    = indOfKeyword(sflPair.sflctl, 'SFLCLR');
        const sfldspPos    = indOfKeyword(sflPair.sflctl, 'SFLDSP');
        const sfldspctlPos = indOfKeyword(sflPair.sflctl, 'SFLDSPCTL');
        const lkey = sflPair.sfl.name.toLowerCase();
        out.push(`       LOAD-SUBFILE.`);
        out.push(`      *> [DSPF-RAD-REGION begin=load-${lkey}]`);
        out.push(`      *> Clear the ${sflPair.sfl.name} subfile, load it record-by-record,`);
        out.push(`      *> then turn on SFLDSP / SFLDSPCTL so the SFLCTL renders the loaded`);
        out.push(`      *> subfile on the next WRITE.`);
        if (sflclrPos != null) {
            out.push(`           MOVE B"1" TO IN${pad2(sflclrPos)}`);
        }
        out.push(`           WRITE ${sflPair.sflctl.name}-REC FORMAT IS "${sflPair.sflctl.name}"`);
        out.push(`              INDICATORS ARE INDICATORS`);
        out.push(`           END-WRITE`);
        if (sflclrPos != null) {
            out.push(`           MOVE B"0" TO IN${pad2(sflclrPos)}`);
        }
        out.push(``);
        out.push(`           MOVE 0 TO WS-SFL-RRN`);
        out.push(`      *> Iterate your data source and add records:`);
        out.push(`      *>   ADD 1 TO WS-SFL-RRN`);
        out.push(`      *>   ... populate ${sflPair.sfl.name}-REC fields ...`);
        out.push(`      *>   WRITE ${sflPair.sfl.name}-REC FORMAT IS "${sflPair.sfl.name}"`);
        out.push(`      *>      INDICATORS ARE INDICATORS`);
        out.push(`      *>   END-WRITE`);
        out.push(``);
        if (sfldspPos != null) {
            out.push(`           MOVE B"1" TO IN${pad2(sfldspPos)}`);
        }
        if (sfldspctlPos != null) {
            out.push(`           MOVE B"1" TO IN${pad2(sfldspctlPos)}`);
        }
        out.push(`      *> [DSPF-RAD-REGION end=load-${lkey}]`);
        out.push(`           .`);
        out.push(``);
    }
    out.push(`       TERMINATE-PROGRAM.`);
    out.push(`      *> [DSPF-RAD-REGION begin=shutdown]`);
    out.push(`      *> Cleanup: close files, log, etc.`);
    out.push(`      *> [DSPF-RAD-REGION end=shutdown]`);
    out.push(`           CLOSE ${dspfName}`);
    out.push(`           .`);

    return out.join('\n') + '\n';
}

// ------------------------------------------------------------ analysis

/** Walk every record's keywords gathering CA/CF/HELP/HOME/PRINT/CLEAR/
 *  ROLLUP/ROLLDOWN/PAGEUP/PAGEDOWN with their indicator number.  Used to
 *  build the INDDS structure for RPGLE and the INDICATOR clauses for
 *  COBOL. */
function collectAids (doc) {
    const seen = new Set();
    const out = [];
    for (const rec of doc.records) {
        for (const kw of rec.keywords ?? []) {
            const m = aidFromKeyword(kw);
            if (!m) continue;
            if (seen.has(m.pos)) continue;
            seen.add(m.pos);
            out.push(m);
        }
    }
    return out.sort((a, b) => a.pos - b.pos);
}

function aidFromKeyword (kw) {
    const name = kw.name;
    let pos;
    if (/^C[AF]\d{1,2}$/.test(name)) {
        const num = parseInt(name.slice(2), 10);
        // Args may carry an explicit indicator number first.
        pos = parseInt(kw.args?.[0], 10);
        if (!Number.isFinite(pos)) pos = num;
        const description = unquote(kw.args?.[1]) || AID_DESCRIPTIONS[name];
        return {
            aid: name,
            pos,
            field: makeFieldName(name, description),
        };
    }
    if (AID_DESCRIPTIONS[name]) {
        pos = parseInt(kw.args?.[0], 10);
        if (!Number.isFinite(pos)) return null;
        return {
            aid: name,
            pos,
            field: makeFieldName(name, AID_DESCRIPTIONS[name]),
        };
    }
    return null;
}

function makeFieldName (aid, description) {
    // Prefer a readable name; collapse "Exit" / "Cancel" / etc., fall
    // back to the AID literal (Ca03) when no description exists.
    const base = (description || aid).replace(/[^A-Za-z0-9]/g, '');
    if (!base) return aid;
    return base[0].toUpperCase() + base.slice(1).toLowerCase();
}

function unquote (s) {
    if (!s) return '';
    const t = String(s).trim();
    if (t.startsWith("'") && t.endsWith("'") && t.length >= 2) {
        return t.substring(1, t.length - 1).replace(/''/g, "'");
    }
    return t;
}

function pickMainRecord (doc) {
    // EXFMT-able record: prefer the record that hosts MNUBARDSP (its
    // EXFMT pulls the menu bar onto the screen), otherwise the first
    // record that's not a sub-component (SFL/PULLDOWN/MNUBAR are stitched
    // onto another EXFMT'd record at runtime, not displayed standalone).
    const withMbDsp = doc.records.find(r =>
        r.keywords?.some(kw => kw.name === 'MNUBARDSP'));
    if (withMbDsp) return withMbDsp;
    for (const r of doc.records) {
        if (r.type === 'SFL') continue;
        if (r.type === 'PULLDOWN') continue;
        if (r.type === 'MNUBAR') continue;
        return r;
    }
    return doc.records[0] ?? null;
}

/** ENPTUI menu bar choices.  Each MNUBARCHC entry on a MNUBAR record's
 *  field is paired with the linked PULLDOWN record's CHOICE entries; the
 *  emitted condition checks both the menu-bar choice number and the
 *  pulldown choice number so each leaf gets its own handler region. */
function collectMenuArms (doc) {
    const arms = [];

    // Find MNUBARDSP somewhere to discover the program-side discriminator
    // field names (the &MNUCHC and &PULL references).  Default to MNUCHC
    // and PULL when missing.
    let mbVar = 'MNUCHC';
    let pdVar = 'PULL';
    for (const rec of doc.records) {
        const md = rec.keywords?.find(kw => kw.name === 'MNUBARDSP');
        if (md) {
            mbVar = stripAmpField(md.args?.[1]) ?? mbVar;
            pdVar = stripAmpField(md.args?.[2]) ?? pdVar;
            break;
        }
    }

    for (const rec of doc.records) {
        if (rec.type !== 'MNUBAR') continue;
        for (const item of rec.items) {
            const mbChcs = item.keywords?.filter(kw => kw.name === 'MNUBARCHC') ?? [];
            for (const mb of mbChcs) {
                const mbNum   = mb.args?.[0];
                const pullRec = mb.args?.[1];
                const mbLabel = unquote(mb.args?.slice(2).join(' '));
                const pull = doc.records.find(r => r.type === 'PULLDOWN' && r.name === pullRec);
                if (!pull || !pull.items.length) {
                    arms.push({
                        condition: `${mbVar} = ${mbNum}`,
                        comment:   `Menu bar: ${mbLabel || '(unlabelled)'}`,
                        regionKey: `mb-${slugify(mbLabel || pullRec || mbNum)}`,
                    });
                    continue;
                }
                for (const pi of pull.items) {
                    const choices = pi.keywords?.filter(kw => kw.name === 'CHOICE') ?? [];
                    if (!choices.length) continue;
                    for (const c of choices) {
                        const cNum   = c.args?.[0];
                        const cLabel = unquote(c.args?.slice(1).join(' '));
                        arms.push({
                            condition: `${mbVar} = ${mbNum} And ${pdVar} = ${cNum}`,
                            comment:   `${mbLabel} > ${cLabel}`,
                            regionKey: `mb-${slugify(mbLabel)}-${slugify(cLabel)}`,
                        });
                    }
                }
            }
        }
    }
    return arms;
}

/** Push buttons (PSHBTNFLD with PSHBTNCHC sub-keywords).  IBM's
 *  canonical spelling is PSHBTN*; we accept the PUSHBTN* variant too.
 *  The field value at runtime is the chosen button number. */
function collectPushbtnArms (doc) {
    const arms = [];
    for (const rec of doc.records) {
        for (const item of rec.items) {
            const isBtnFld = item.keywords?.some(kw =>
                kw.name === 'PUSHBTNFLD' || kw.name === 'PSHBTNFLD');
            if (!isBtnFld) continue;
            const chcs = item.keywords.filter(kw =>
                kw.name === 'PUSHBTNCHC' || kw.name === 'PSHBTNCHC');
            for (const c of chcs) {
                const num   = c.args?.[0];
                const label = unquote(c.args?.slice(1).join(' '));
                arms.push({
                    condition: `${item.name} = ${num}`,
                    comment:   `Push button: ${label}`,
                    regionKey: `btn-${slugify(item.name)}-${slugify(label || num)}`,
                });
            }
        }
    }
    return arms;
}

/** Standalone choice fields (SNGCHCFLD / MLTCHCFLD) NOT living inside a
 *  PULLDOWN record - those are already handled via the menu bar arms. */
function collectChoiceArms (doc) {
    const arms = [];
    for (const rec of doc.records) {
        if (rec.type === 'PULLDOWN') continue;
        for (const item of rec.items) {
            const isSng = item.keywords?.some(kw => kw.name === 'SNGCHCFLD');
            const isMlt = item.keywords?.some(kw => kw.name === 'MLTCHCFLD');
            if (!isSng && !isMlt) continue;
            const chcs = item.keywords.filter(kw => kw.name === 'CHOICE');
            for (const c of chcs) {
                const num   = c.args?.[0];
                const label = unquote(c.args?.slice(1).join(' '));
                arms.push({
                    condition: `${item.name} = ${num}`,
                    comment:   `${isSng ? 'Radio' : 'Check'} (${item.name}): ${label}`,
                    regionKey: `choice-${slugify(item.name)}-${slugify(label || num)}`,
                });
            }
        }
    }
    return arms;
}

function stripAmpField (s) {
    if (!s) return null;
    const t = String(s).trim();
    if (!t) return null;
    return t.replace(/^&/, '').replace(/;$/, '').trim() || null;
}

function slugify (s) {
    return String(s ?? '').toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 40) || 'action';
}

/** Translate a free-form RPGLE-ish boolean ('A = 1 And B = 2') into
 *  COBOL-friendly text ('A = 1 AND B = 2'). */
function cobolCondition (s) {
    return String(s).replace(/\bAnd\b/g, 'AND').replace(/\bOr\b/g, 'OR');
}

function pickSubfilePair (doc) {
    for (const ctl of doc.records) {
        if (ctl.type !== 'SFLCTL') continue;
        const link = ctl.keywords.find(kw => kw.name === 'SFLCTL');
        if (!link || !link.args.length) continue;
        const sfl = doc.records.find(r => r.name === link.args[0] && r.type === 'SFL');
        if (sfl) return { sfl, sflctl: ctl };
    }
    return null;
}

function pad2 (n) { return String(n).padStart(2, '0'); }
